name: Draft PDF
on:
  push:
    paths:
      - paper.md
      - paper.bib
      - .github/workflows/draft-pdf.yml

# Add permissions block
permissions:
  contents: write
  pull-requests: write

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: paper.md
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper.pdf
      - name: Commit PDF to repository
        uses: EndBug/add-and-commit@v9
        with:
          message: "(auto) Paper PDF Draft"
          add: "paper.pdf"
